name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        run: |
          docker build -t my-fastapi-app .
          docker run -d -p 8000:8000 my-fastapi-app

      - name: SSH into Server and Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.UBUNTU_SSH_KEY }}
          SERVER_USER: ${{ secrets.SERVERUSER1 }}
          SERVER_HOST: ${{ secrets.SERVERHOST1 }}
          DEPLOY_PATH: "/home/ubuntu/fastapi-book-project"  

        run: |
          echo "$UBUNTU_SSH_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $SERVERUSER1@$SERVERHOST1 << 'EOF'
            cd $DEPLOY_PATH
            git fetch origin main
            git reset --hard origin/main
            # stop existing container
            docker compose down
            docker compose up --build -d
          EOF
