name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH into Server and Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVERUSER1 }}
          SERVER_HOST: ${{ secrets.SERVERHOST1 }}
          DEPLOY_PATH: "/home/ubuntu/fastapi-book-project"  # Update this with your actual path

        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $SERVERUSER1@$SERVERHOST1 << 'EOF'
            set -e  # Exit on error
            
            # Navigate to deployment directory
            cd $DEPLOY_PATH
            
            # Ensure latest code is pulled correctly
            git fetch origin main
            git reset --hard origin/main
            git pull origin main
            
            # Restart application using Docker
            docker compose down
            docker compose up --build -d
          EOF

