name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        run: |
          cd ~/fastapi-book-project
          git pull origin main
          docker-compose down
          docker-compose up -d --build
